In [1]:
from parsing.parse_functions import parse_pdb_files
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.patches import Circle
import matplotlib
from matplotlib.patches import Circle
from mpl_toolkits.mplot3d import Axes3D   # noqa: F401  (needed for 3-D projection)
from scipy.cluster.hierarchy import average as average_linkage
from scipy.cluster.hierarchy import single as single_linkage
from scipy.cluster.hierarchy import fcluster
# for computing the distance matrix:
from scipy.spatial.distance import pdist, squareform
import pickle
import os

from utils.scale_low_res_coordinates import scale_low_res_coords
from utils.pucker_data_functions import determine_pucker_data
from shape_analysis import pre_clustering
from utils.pucker_data_functions import sort_data_into_cluster
from pnds.PNDS_RNA_clustering import new_multi_slink
from utils import plot_functions
from pnds.PNDS_PNS import PNS, unfold_points, as_matrix
from pnds.PNS_mode_hunter import PNSModeHunter, refine_clusters_with_pns

In [2]:
input_pdb_dir = "/Users/kaisardauletbek/Documents/GitHub/RNA-Classification/data/rna2020_pruned_pdbs/"
suites = parse_pdb_files(input_pdb_dir, input_pdb_folder=input_pdb_dir)

puckers = ['c2c2', 'c2c3', 'c3c2', 'c3c3']
pucker_indices = {}
for pucker in puckers:
    indices, _ = determine_pucker_data(suites, pucker)
    pucker_indices[pucker] = indices

pucker_indices = {k: np.asarray(v, dtype=np.intp)   
                  for k, v in pucker_indices.items()}


In [3]:
suites[0].low_resolution_coordinates()

[[-1.86582107e+00  4.66959699e+00  1.31621644e+00]
 [-2.29741622e+00  4.18906717e+00  1.60215818e-16]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 3.14319873e+00  4.18906717e+00  1.34261672e-16]
 [ 2.87275614e+00  4.18901675e+00  1.42876268e+00]]


[4.777698713816097,
 5.237173092423049,
 65.62388562608349,
 72.88010355176152,
 20.056338853094566,
 100.71839359733033,
 -0.0020217340379483136]

In [4]:
def spherical_to_vec(theta_deg: np.ndarray, phi_deg: np.ndarray) -> np.ndarray:
    t, p = np.radians(theta_deg), np.radians(phi_deg)
    return np.column_stack([np.sin(t) * np.cos(p),
                            np.sin(t) * np.sin(p),
                            np.cos(t)])

def arc_distance(a: np.ndarray, b: float) -> np.ndarray:
    """Shortest signed arc distance between vectors of angles a and scalar b (radians)."""
    d = (a - b + np.pi) % (2 * np.pi) - np.pi
    return d

def exponential_map(V, p):
    """
    V - point cloud N x R^m
    p - point of tangency R^m
    """
    N, M = V.shape[0], V.shape[1]
    V_mean = V.mean(axis=0)
    # check if points are centered at 0, center them
    V -= V_mean
    V = np.column_stack([V, np.zeros(N)])
    V_norm = np.linalg.norm(V, axis=1)[:, None]
    
    return np.cos(V_norm) * p + np.sin(V_norm) * (V / V_norm)
    
    
# if p[0] == 1:
#     rest_basis = gram_schmidt(np.vstack[p, np.eye(d)[1:]]))[1:]
# else:
#     rest_basis = gram_schmidt(np.vstack[p, np.eye(d)[:-1]]))[1:]

In [5]:
# scale only the distance‐variance, leave α‐variance and both means alone
scaled_coords, lambda_d, lambda_alpha = scale_low_res_coords(
    suites,
    scale_distance_variance=True,
    scale_alpha_variance=False,
    preserve_distance_mean=True,
    preserve_alpha_mean=True,
    store_attr="scaled_dvar_only"
)

d2_s, d3_s, alpha_s, theta1, phi1, theta2, phi2 = scaled_coords.T
N = len(d2_s)

[[-1.78065690e+00  4.86624649e+00  1.24921219e+00]
 [-2.23518427e+00  4.27686057e+00  1.60707125e-16]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 3.40875310e+00  4.27686057e+00 -3.68221253e-16]
 [ 3.13842321e+00  4.46425757e+00  1.46250508e+00]]
[[-2.12432457e+00  4.68602038e+00  1.35243194e+00]
 [-2.33537783e+00  4.12408589e+00  6.00800808e-16]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 3.31535708e+00  4.12408589e+00  5.18794204e-16]
 [ 2.74013633e+00  4.25149017e+00  1.33167910e+00]]
[[-1.91850423e+00  4.59405944e+00  1.42898928e+00]
 [-2.11338396e+00  4.20788133e+00 -2.32175662e-17]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 3.38932792e+00  4.20788133e+00  5.03874065e-17]
 [ 2.90575490e+00  4.21041527e+00  1.36524749e+00]]
[[-1.92050746e+00  4.64527394e+00  1.40922181e+00]
 [-2.20335124e+00  4.25679578e+00  1.02860132e-16]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 2.95953420e+00  4.25679578e+00  1.12343923e-16]
 [ 2.65061237e+00  4.1564953

In [6]:
# x = np.array([d2_s[0], d3_s[0], alpha_s[0], theta1[0], phi1[0], theta2[0], phi2[0]])
# x_prime = np.array([d2_s[1], d3_s[1], alpha_s[1], theta1[1], phi1[1], theta2[1], phi2[1]])

In [7]:
# np.dot(x, x_prime)

In [8]:
# def get_distance(x, x_prime):
#     return np.dot(x, x_prime)

# def get_distance_matrix(scaled_coords):
#     d2_s, d3_s, alpha_s, theta1, phi1, theta2, phi2 = scaled_coords.T
#     N = len(d2_s)
#     distance_matrix = np.zeros((N, N))
#     for i in range(N):
#         for j in range(i+1, N):
#             x = np.array([d2_s[i], d3_s[i], alpha_s[i], theta1[i], phi1[i], theta2[i], phi2[i]])
#             x_prime = np.array([d2_s[j], d3_s[j], d3_s[j], theta1[j], phi1[j], theta2[j], phi2[j]])
#             distance_matrix[i, j] = get_distance(x, x_prime)
#     return distance_matrix

# # distance_matrix = get_distance_matrix(scaled_coords)


In [9]:
# scaled_coords[pucker_indices['c3c3']].shape

In [33]:
# names = ['c3c3', 'c3c2', 'c2c3', 'c2c2', 'all']
# min_size = 3

# configurations = [
#     ('c2c2', 0.02, 0.05),
#     ('c2c3', 0.02, 0.07),
#     ('c3c2', 0.02, 0.05),
#     ('c3c3', 0.02, 0.09),
# ]

# # Folder to store preclustering results
# os.makedirs('preclustering_results', exist_ok=True)

# for name, outlier, qf in configurations:
#     scaled_coords_by_pucker = scaled_coords[pucker_indices[name]]
    
#     clusters, outliers, _ = pre_clustering(
#         input_data = scaled_coords_by_pucker,
#         m = min_size,
#         percentage = 0.0,  # or outlier if needed
#         string_folder = "out/clustering_low_res",
#         method = average_linkage,
#         q_fold = qf,
#         distance = "low_res_suite_shape"
#     )

#     # Save precluster results to .pkl
#     result = {
#         'name': name,
#         'clusters': clusters,
#         'outliers': outliers,
#         'scaled_coords': scaled_coords_by_pucker
#     }
#     with open(f'preclustering_results/{name}_precluster.pkl', 'wb') as f:
#         pickle.dump(result, f)

#     # Optional: also plot & inspect
#     sorted_clusters = sorted(clusters, key=len, reverse=True)
#     cluster_sizes = [len(c) for c in sorted_clusters]
#     print(f"[{name}] cluster sizes:", cluster_sizes)

#     data_by_cluster, _ = sort_data_into_cluster(scaled_coords_by_pucker, sorted_clusters, min_size)
#     plot_functions.scatter_plots(
#         data_by_cluster,
#         filename=f"low_res_suite_shape_average_linkage_{name}",
#         set_title=f"low_res_suite_shape_average_linkage {name}",
#         suite_titles=[r'$d_2$', r'$d_3$', r'$\alpha$', r'$\theta_1$', r'$\phi_1$', r'$\theta_2$', r'$\phi_2$'],
#         list_ranges=[[3,5.5],[4,6.5],[0,180],[0,180],[-180,180],[0,180],[-180,180]],
#         number_of_elements=cluster_sizes,
#         legend=True,
#         s=20
#     )


In [9]:
# # 0 to 1

# import os
# import pickle
# import numpy as np

# # Configuration
# min_size = 3
# q_fold_values = np.round(np.arange(0.0, 1.01, 0.1), 2)  # [0.0, 0.1, ..., 1.0]

# # pucker configurations: (name, lower bound, upper bound)
# configurations = [
#     ('c2c2', 0.02, 0.05),
#     ('c2c3', 0.02, 0.07),
#     ('c3c2', 0.02, 0.05),
#     ('c3c3', 0.02, 0.09),
# ]

# # Create the base folder for experiments
# base_dir = 'q_fold_experiments'
# os.makedirs(base_dir, exist_ok=True)

# for name, lb, ub in configurations:
#     # Make a subfolder for this configuration
#     config_dir = os.path.join(base_dir, name)
#     os.makedirs(config_dir, exist_ok=True)

#     scaled_coords_by_pucker = scaled_coords[pucker_indices[name]]

#     for qf in q_fold_values:
#         clusters, outliers, _ = pre_clustering(
#             input_data=scaled_coords_by_pucker,
#             m=min_size,
#             percentage=0.0,
#             string_folder="out/clustering_low_res",
#             method=single_linkage,
#             q_fold=qf,
#             distance="low_res_suite_shape"
#         )

#         # Save results if needed
#         result = {
#             'name': name,
#             'q_fold': qf,
#             'clusters': clusters,
#             'outliers': outliers,
#             'scaled_coords': scaled_coords_by_pucker
#         }
#         pkl_path = os.path.join(config_dir, f'precluster_qf_{qf:.1f}.pkl')
#         with open(pkl_path, 'wb') as f:
#             pickle.dump(result, f)

#         # Plot clusters
#         sorted_clusters = sorted(clusters, key=len, reverse=True)
#         cluster_sizes = [len(c) for c in sorted_clusters]
#         data_by_cluster, _ = sort_data_into_cluster(scaled_coords_by_pucker, sorted_clusters, min_size)

#         plot_path = os.path.join(config_dir, f'plot_qf_{qf:.1f}.png')
#         plot_functions.scatter_plots(
#             data_by_cluster,
#             filename=plot_path,
#             set_title=f"low_res_suite_shape_single_linkage {name} (qf={qf:.1f})",
#             suite_titles=[r'$d_2$', r'$d_3$', r'$\alpha$', r'$\theta_1$', r'$\phi_1$', r'$\theta_2$', r'$\phi_2$'],
#             list_ranges=[[3,5.5],[4,6.5],[0,180],[0,180],[-180,180],[0,180],[-180,180]],
#             number_of_elements=cluster_sizes,
#             legend=True,
#             s=20
#         )

#         print(f"[{name}] q_fold={qf:.1f} → clusters: {cluster_sizes}")


In [20]:
import os
import pickle
import numpy as np

# Configuration
min_size = 3

# Define pucker configurations with specific q_fold ranges
configurations = {
    # 'c2c2': np.round(np.arange(0.00, 0.101, 0.01), 3),
    # 'c2c3': np.round(np.arange(0.00, 0.101, 0.01), 3),
    # 'c3c2': np.round(np.arange(0.00, 0.101, 0.01), 3),
    'c3c3': np.round(np.arange(0.001, 0.0101, 0.001), 3),
}

# Create the base folder for experiments
base_dir = 'q_fold_experiments'
os.makedirs(base_dir, exist_ok=True)

for name, q_fold_values in configurations.items():
    config_dir = os.path.join(base_dir, name)
    os.makedirs(config_dir, exist_ok=True)

    scaled_coords_by_pucker = scaled_coords[pucker_indices[name]]

    for qf in q_fold_values:
        print(f"QF: {qf}")
        clusters, outliers, _ = pre_clustering(
            input_data=scaled_coords_by_pucker,
            m=min_size,
            percentage=0.0,
            string_folder="out/clustering_low_res",
            method=single_linkage,
            q_fold=qf,
            distance="low_res_suite_shape"
        )

        # Save results
        result = {
            'name': name,
            'q_fold': qf,
            'clusters': clusters,
            'outliers': outliers,
            'scaled_coords': scaled_coords_by_pucker
        }
        pkl_path = os.path.join(config_dir, f'precluster_qf_{qf:.2f}.pkl')
        with open(pkl_path, 'wb') as f:
            pickle.dump(result, f)

        # Plot clusters
        sorted_clusters = sorted(clusters, key=len, reverse=True)
        cluster_sizes = [len(c) for c in sorted_clusters]
        data_by_cluster, _ = sort_data_into_cluster(scaled_coords_by_pucker, sorted_clusters, min_size)

        plot_path = os.path.join(config_dir, f'plot_qf_{qf:.2f}.png')
        plot_functions.scatter_plots(
            data_by_cluster,
            filename=plot_path,
            set_title=f"low_res_suite_shape_single_linkage {name} (qf={qf:.3f})",
            suite_titles=[r'$d_2$', r'$d_3$', r'$\alpha$', r'$\theta_1$', r'$\phi_1$', r'$\theta_2$', r'$\phi_2$'],
            list_ranges=[[3,5.5],[4,6.5],[0,180],[0,180],[-180,180],[0,180],[-180,180]],
            number_of_elements=cluster_sizes,
            legend=True,
            s=20
        )

        print(f"[{name}] q_fold={qf:.2f} → clusters: {cluster_sizes}")


QF: 0.001
no shape_space
3585
59.94997914928745
2.7258689854369056
[c3c3] q_fold=0.00 → clusters: [3585]
QF: 0.002
no shape_space
3585
59.94997914928745
2.7258689854369056
[c3c3] q_fold=0.00 → clusters: [3585]
QF: 0.003
no shape_space
3585
59.94997914928745
2.7258689854369056
[c3c3] q_fold=0.00 → clusters: [3585]
QF: 0.004
no shape_space
3585
59.94997914928745
2.7258689854369056
[c3c3] q_fold=0.00 → clusters: [3585]
QF: 0.005
no shape_space
3585
59.94997914928745
2.7258689854369056
[c3c3] q_fold=0.01 → clusters: [3585]
QF: 0.006
no shape_space
3585
59.94997914928745
2.7258689854369056
[c3c3] q_fold=0.01 → clusters: [3585]
QF: 0.007
no shape_space
3585
59.94997914928745
2.7258689854369056
[c3c3] q_fold=0.01 → clusters: [3585]
QF: 0.008
no shape_space
3585
59.94997914928745
2.7258689854369056
[c3c3] q_fold=0.01 → clusters: [3585]
QF: 0.009
no shape_space
3585
59.94997914928745
2.7258689854369056
[c3c3] q_fold=0.01 → clusters: [3585]
QF: 0.01
no shape_space
3585
59.94997914928745
2.725868

In [19]:
configurations

{'c3c3': array([0.   , 0.001, 0.002, 0.003, 0.004, 0.005, 0.006, 0.007, 0.008,
        0.009, 0.01 ])}

In [10]:
result_dir = 'preclustering_results'

mode_clusters_res = []

for filename in os.listdir(result_dir):
    if filename.endswith('_precluster.pkl'):
        # Load
        with open(os.path.join(result_dir, filename), 'rb') as f:
            result = pickle.load(f)
            print(len(result['clusters']))

11
9
8
5


In [8]:
min_size = 3
scale = 12000

# Where you saved them
result_dir = 'preclustering_results'

mode_clusters_res = []

for filename in os.listdir(result_dir):
    if filename.endswith('_precluster.pkl'):
        # Load
        with open(os.path.join(result_dir, filename), 'rb') as f:
            result = pickle.load(f)

        name = result['name']
        clusters = result['clusters']
        outliers = result['outliers']
        scaled_coords_by_pucker = result['scaled_coords']

        print(name)

        # Map to sphere and angles for PNS input
        d2_s, d3_s, alpha_s, theta1, phi1, theta2, phi2 = scaled_coords_by_pucker.T

        # TODO run PN_G_S on (theta_i, phi_i), self.dists_ will return residuals, dists_[0] = theta, dists_[1] = phi since we're on S2
        S2_1 = spherical_to_vec(theta1, phi1)
        pns_S2_1 = PNS(mode='great', verbose=True).fit(S2_1)
        theta1, phi1 = pns_S2_1.dists_

        S2_2 = spherical_to_vec(theta2, phi2)
        pns_S2_2 = PNS(mode='great', verbose=True).fit(S2_2)
        theta2, phi2 = pns_S2_2.dists_

        # TODO substract the mean from d_i_s 
        V = np.column_stack([d2_s, d3_s])
        V -= np.mean(V, axis=0)

        # TODO run PN_G_S on S2_d (distances)
        # S2_pts = exponential_map(V, p=np.array([0,0,1]))
        S2_d = exponential_map(V, p=np.array([0,0,1])) # try this should be better
        pns_S2_d = PNS(mode='great', verbose=True).fit(S2_d)
        theta_d, phi_d = pns_S2_d.dists_

        # r = np.linalg.norm(S2_pts, axis=1)
        # theta_e_deg = np.degrees(np.arccos(np.clip(z/r, -1, 1)))
        # phi_e_deg = (np.degrees(np.arctan2(y, x)) + 360.0) % 360.0

        # TODO maybe add 180 for plots
        angle_matrix = np.column_stack([
            theta_d + 180,
            phi_d + 180,
            alpha_s,
            theta1 + 180,
            phi1 + 180,
            theta2 + 180,
            phi2 + 180
        ])
        # if filename == 'c2c2_precluster.pkl':
        #     break

        # Run PNS-based clustering
        mode_clusters, _ = refine_clusters_with_pns(
            scale=scale,
            data=angle_matrix,
            cluster_list=clusters,
            outlier_list=outliers,
            min_cluster_size=min_size
        )

        mode_clusters_res.append({
            'name': name,
            'mode_clusters': mode_clusters
        })

        print(f"[{name}] mode clusters done: {len(mode_clusters)} clusters")

# You can save final mode_clusters_res if needed
with open('mode_clusters_results.pkl', 'wb') as f:
    pickle.dump(mode_clusters_res, f)


c3c3
Starting PNS-based cluster refinement...
  Trying mode: SI_gap
  Trying mode: SO_gap
  Trying mode: SI_mean


/Users/kaisardauletbek/Documents/GitHub/RNA-Classification/mintage/pnds/PNDS_PNS.py:414: RuntimeWarning: Number of calls to function has reached maxfev = 1000.
  result, exit_code = leastsq(f, initial)
/Users/kaisardauletbek/Documents/GitHub/RNA-Classification/mintage/pnds/PNDS_PNS.py:439: RuntimeWarning: Number of calls to function has reached maxfev = 1000.
  result, exit_code = leastsq(f, initial, ftol=tol, xtol=tol)


  Trying mode: SO_mean
    Plotting best residuals (mode: SO_mean, variance: 0.808)
    No valid PNS projections found. Plotting diagnostics before fallback.
    Falling back to large cluster separation.


KeyboardInterrupt: 

In [10]:
angle_matrix.shape

(3585, 7)

'name': 'c3c2',
 'optimal_q_fold': 0.37,


 'name': 'c2c2',
 'optimal_q_fold': 0.31,

 'name': 'c3c2',
  'optimal_q_fold': 0.37,

q_fold=0.35 for c3c3, found 7 clusters