In [2]:
from parsing.parse_functions import parse_pdb_files
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.patches import Circle
import matplotlib
from matplotlib.patches import Circle
from mpl_toolkits.mplot3d import Axes3D   # noqa: F401  (needed for 3-D projection)
from scipy.cluster.hierarchy import average as average_linkage
from scipy.cluster.hierarchy import single as single_linkage
from scipy.cluster.hierarchy import fcluster
# for computing the distance matrix:
from scipy.spatial.distance import pdist, squareform
import pickle
import os

from utils.scale_low_res_coordinates import scale_low_res_coords
from utils.pucker_data_functions import determine_pucker_data
from shape_analysis import pre_clustering
from utils.pucker_data_functions import sort_data_into_cluster
from pnds.PNDS_RNA_clustering import new_multi_slink
from utils import plot_functions
from pnds.PNDS_PNS import PNS, unfold_points, as_matrix
from pnds.PNS_mode_hunter import PNSModeHunter, refine_clusters_with_pns
from utils.Suite_class import Suite

In [66]:
input_pdb_dir = "/Users/kaisardauletbek/Documents/GitHub/RNA-Classification/data/rna2020_pruned_pdbs/"
suites = parse_pdb_files(input_pdb_dir, input_pdb_folder=input_pdb_dir)

puckers = ['c2c2', 'c2c3', 'c3c2', 'c3c3']
pucker_indices = {}
for pucker in puckers:
    indices, _ = determine_pucker_data(suites, pucker)
    pucker_indices[pucker] = indices

pucker_indices = {k: np.asarray(v, dtype=np.intp)   
                  for k, v in pucker_indices.items()}


In [67]:
suites[523].answer

In [5]:
suites[0].low_resolution_coordinates()

[np.float64(4.777698713816097),
 np.float64(5.237173092423049),
 np.float64(65.62388562608349),
 np.float64(72.88010355176152),
 np.float64(20.05633885309457),
 np.float64(100.71839359733033),
 np.float64(-0.0020217340379483136)]

In [34]:
def spherical_to_vec(theta_deg: np.ndarray, phi_deg: np.ndarray) -> np.ndarray:
    t, p = np.radians(theta_deg), np.radians(phi_deg)
    return np.column_stack([np.sin(t) * np.cos(p),
                            np.sin(t) * np.sin(p),
                            np.cos(t)])

def arc_distance(a: np.ndarray, b: float) -> np.ndarray:
    """Shortest signed arc distance between vectors of angles a and scalar b (radians)."""
    d = (a - b + np.pi) % (2 * np.pi) - np.pi
    return d

def exponential_map(V, p):
    """
    V - point cloud N x R^m
    p - point of tangency R^m
    """
    N, M = V.shape[0], V.shape[1]
    V_mean = V.mean(axis=0)
    # check if points are centered at 0, center them
    V -= V_mean
    V = np.column_stack([V, np.zeros(N)])
    V_norm = np.linalg.norm(V, axis=1)[:, None]
    
    return np.cos(V_norm) * p + np.sin(V_norm) * (V / V_norm)
    
    
# if p[0] == 1:
#     rest_basis = gram_schmidt(np.vstack[p, np.eye(d)[1:]]))[1:]
# else:
#     rest_basis = gram_schmidt(np.vstack[p, np.eye(d)[:-1]]))[1:]

In [35]:
# scale only the distance‐variance, leave α‐variance and both means alone
scaled_coords, lambda_d, lambda_alpha = scale_low_res_coords(
    suites,
    scale_distance_variance=True,
    scale_alpha_variance=False,
    preserve_distance_mean=True,
    preserve_alpha_mean=True,
    store_attr="scaled_dvar_only"
)

d2_s, d3_s, alpha_s, theta1, phi1, theta2, phi2 = scaled_coords.T
N = len(d2_s)

In [6]:
# x = np.array([d2_s[0], d3_s[0], alpha_s[0], theta1[0], phi1[0], theta2[0], phi2[0]])
# x_prime = np.array([d2_s[1], d3_s[1], alpha_s[1], theta1[1], phi1[1], theta2[1], phi2[1]])

In [7]:
# np.dot(x, x_prime)

In [8]:
# def get_distance(x, x_prime):
#     return np.dot(x, x_prime)

# def get_distance_matrix(scaled_coords):
#     d2_s, d3_s, alpha_s, theta1, phi1, theta2, phi2 = scaled_coords.T
#     N = len(d2_s)
#     distance_matrix = np.zeros((N, N))
#     for i in range(N):
#         for j in range(i+1, N):
#             x = np.array([d2_s[i], d3_s[i], alpha_s[i], theta1[i], phi1[i], theta2[i], phi2[i]])
#             x_prime = np.array([d2_s[j], d3_s[j], d3_s[j], theta1[j], phi1[j], theta2[j], phi2[j]])
#             distance_matrix[i, j] = get_distance(x, x_prime)
#     return distance_matrix

# # distance_matrix = get_distance_matrix(scaled_coords)


In [9]:
# scaled_coords[pucker_indices['c3c3']].shape

In [33]:
# names = ['c3c3', 'c3c2', 'c2c3', 'c2c2', 'all']
# min_size = 3

# configurations = [
#     ('c2c2', 0.02, 0.05),
#     ('c2c3', 0.02, 0.07),
#     ('c3c2', 0.02, 0.05),
#     ('c3c3', 0.02, 0.09),
# ]

# # Folder to store preclustering results
# os.makedirs('preclustering_results', exist_ok=True)

# for name, outlier, qf in configurations:
#     scaled_coords_by_pucker = scaled_coords[pucker_indices[name]]
    
#     clusters, outliers, _ = pre_clustering(
#         input_data = scaled_coords_by_pucker,
#         m = min_size,
#         percentage = 0.0,  # or outlier if needed
#         string_folder = "out/clustering_low_res",
#         method = average_linkage,
#         q_fold = qf,
#         distance = "low_res_suite_shape"
#     )

#     # Save precluster results to .pkl
#     result = {
#         'name': name,
#         'clusters': clusters,
#         'outliers': outliers,
#         'scaled_coords': scaled_coords_by_pucker
#     }
#     with open(f'preclustering_results/{name}_precluster.pkl', 'wb') as f:
#         pickle.dump(result, f)

#     # Optional: also plot & inspect
#     sorted_clusters = sorted(clusters, key=len, reverse=True)
#     cluster_sizes = [len(c) for c in sorted_clusters]
#     print(f"[{name}] cluster sizes:", cluster_sizes)

#     data_by_cluster, _ = sort_data_into_cluster(scaled_coords_by_pucker, sorted_clusters, min_size)
#     plot_functions.scatter_plots(
#         data_by_cluster,
#         filename=f"low_res_suite_shape_average_linkage_{name}",
#         set_title=f"low_res_suite_shape_average_linkage {name}",
#         suite_titles=[r'$d_2$', r'$d_3$', r'$\alpha$', r'$\theta_1$', r'$\phi_1$', r'$\theta_2$', r'$\phi_2$'],
#         list_ranges=[[3,5.5],[4,6.5],[0,180],[0,180],[-180,180],[0,180],[-180,180]],
#         number_of_elements=cluster_sizes,
#         legend=True,
#         s=20
#     )


In [40]:
# 0 to 1

import os
import pickle
import numpy as np

# Configuration
min_size = 3
q_fold_values = np.round(np.arange(0.0, 1.01, 0.1), 2)  # [0.0, 0.1, ..., 1.0]

# pucker configurations: (name, lower bound, upper bound)
configurations = [
    ('c2c2', 0.02, 0.08),
    ('c2c3', 0.02, 0.19),
    ('c3c2', 0.02, 0.09),
    ('c3c3', 0.02, 0.11),
]

# Create the base folder for experiments
base_dir = 'q_fold_experiments'
os.makedirs(base_dir, exist_ok=True)

for name, outlier_pct, qf in configurations:
    # Make a subfolder for this configuration
    config_dir = os.path.join(base_dir, name)
    os.makedirs(config_dir, exist_ok=True)

    scaled_coords_by_pucker = scaled_coords[pucker_indices[name]]

    clusters, outliers, _ = pre_clustering(
        input_data=scaled_coords_by_pucker,
        m=min_size,
        percentage=outlier_pct,
        string_folder="out/clustering_low_res",
        method=average_linkage,
        q_fold=qf,
        distance="low_res_suite_shape"
    )

    # Save results if needed
    result = {
        'name': name,
        'q_fold': qf,
        'clusters': clusters,
        'outliers': outliers,
        'scaled_coords': scaled_coords_by_pucker
    }
    pkl_path = os.path.join(config_dir, f'precluster_qf_{qf}.pkl')
    with open(pkl_path, 'wb') as f:
        pickle.dump(result, f)

    # Plot clusters
    sorted_clusters = sorted(clusters, key=len, reverse=True)
    cluster_sizes = [len(c) for c in sorted_clusters]
    data_by_cluster, _ = sort_data_into_cluster(scaled_coords_by_pucker, sorted_clusters, min_size)

    plot_path = os.path.join(config_dir, f'plot_qf_{qf}.png')
    plot_functions.scatter_plots(
        data_by_cluster,
        filename=plot_path,
        set_title=f"low_res_suite_shape_single_linkage {name} (qf={qf:.1f})",
        suite_titles=[r'$d_2$', r'$d_3$', r'$\alpha$', r'$\theta_1$', r'$\phi_1$', r'$\theta_2$', r'$\phi_2$'],
        list_ranges=[[3,5.5],[4,6.5],[0,180],[0,180],[-180,180],[0,180],[-180,180]],
        number_of_elements=cluster_sizes,
        legend=True,
        s=20
    )

    print(f"[{name}] q_fold={qf:.1f} → clusters: {cluster_sizes}")


no shape_space
136
12.041594578792296
85
9.695359714832659
61
8.366600265340756
35
6.6332495807108
10
4.358898943540674
1.6041672578329635
[c2c2] q_fold=0.1 → clusters: [51, 26, 25, 23, 10]
no shape_space
217
15.033296378372908
181
13.784048752090222
125
11.575836902790225
61
8.366600265340756
31
6.324555320336759
16
5.0
1.0377688240469163
[c2c3] q_fold=0.2 → clusters: [64, 56, 36, 30, 16, 15]
no shape_space
264
16.522711641858304
204
14.594519519326424
75
9.16515138991168
32
6.4031242374328485
19
5.291502622129181
8
4.123105625617661
1.3079247105554603
[c3c2] q_fold=0.1 → clusters: [129, 60, 43, 13, 11, 8]
no shape_space
3539
59.565090447341724
3400
58.38664230798
2441
49.49747468305833
554
23.727621035409346
373
19.544820285692065
244
15.905973720586866
152
12.68857754044952
101
10.488088481701515
72
9.0
47
7.483314773547883
26
5.916079783099616
9
4.242640687119285
0.6165396478139755
[c3c3] q_fold=0.1 → clusters: [1885, 957, 181, 138, 129, 90, 51, 29, 25, 21, 17, 9]


In [20]:
# import os
# import pickle
# import numpy as np

# # Configuration
# min_size = 3

# # Define pucker configurations with specific q_fold ranges
# configurations = {
#     'c2c2': np.round(np.arange(0.00, 0.101, 0.01), 3),
#     'c2c3': np.round(np.arange(0.00, 0.101, 0.01), 3),
#     'c3c2': np.round(np.arange(0.00, 0.101, 0.01), 3),
#     'c3c3': np.round(np.arange(0.001, 0.0101, 0.001), 3),
# }

# # Create the base folder for experiments
# base_dir = 'q_fold_experiments'
# os.makedirs(base_dir, exist_ok=True)

# for name, q_fold_values in configurations.items():
#     config_dir = os.path.join(base_dir, name)
#     os.makedirs(config_dir, exist_ok=True)

#     scaled_coords_by_pucker = scaled_coords[pucker_indices[name]]

#     for qf in q_fold_values:
#         print(f"QF: {qf}")
#         clusters, outliers, _ = pre_clustering(
#             input_data=scaled_coords_by_pucker,
#             m=min_size,
#             percentage=0.0,
#             string_folder="out/clustering_low_res",
#             method=single_linkage,
#             q_fold=qf,
#             distance="low_res_suite_shape"
#         )

#         # Save results
#         result = {
#             'name': name,
#             'q_fold': qf,
#             'clusters': clusters,
#             'outliers': outliers,
#             'scaled_coords': scaled_coords_by_pucker
#         }
#         pkl_path = os.path.join(config_dir, f'precluster_qf_{qf:.2f}.pkl')
#         with open(pkl_path, 'wb') as f:
#             pickle.dump(result, f)

#         # Plot clusters
#         sorted_clusters = sorted(clusters, key=len, reverse=True)
#         cluster_sizes = [len(c) for c in sorted_clusters]
#         data_by_cluster, _ = sort_data_into_cluster(scaled_coords_by_pucker, sorted_clusters, min_size)

#         plot_path = os.path.join(config_dir, f'plot_qf_{qf:.2f}.png')
#         plot_functions.scatter_plots(
#             data_by_cluster,
#             filename=plot_path,
#             set_title=f"low_res_suite_shape_single_linkage {name} (qf={qf:.3f})",
#             suite_titles=[r'$d_2$', r'$d_3$', r'$\alpha$', r'$\theta_1$', r'$\phi_1$', r'$\theta_2$', r'$\phi_2$'],
#             list_ranges=[[3,5.5],[4,6.5],[0,180],[0,180],[-180,180],[0,180],[-180,180]],
#             number_of_elements=cluster_sizes,
#             legend=True,
#             s=20
#         )

#         print(f"[{name}] q_fold={qf:.2f} → clusters: {cluster_sizes}")


QF: 0.001
no shape_space
3585
59.94997914928745
2.7258689854369056
[c3c3] q_fold=0.00 → clusters: [3585]
QF: 0.002
no shape_space
3585
59.94997914928745
2.7258689854369056
[c3c3] q_fold=0.00 → clusters: [3585]
QF: 0.003
no shape_space
3585
59.94997914928745
2.7258689854369056
[c3c3] q_fold=0.00 → clusters: [3585]
QF: 0.004
no shape_space
3585
59.94997914928745
2.7258689854369056
[c3c3] q_fold=0.00 → clusters: [3585]
QF: 0.005
no shape_space
3585
59.94997914928745
2.7258689854369056
[c3c3] q_fold=0.01 → clusters: [3585]
QF: 0.006
no shape_space
3585
59.94997914928745
2.7258689854369056
[c3c3] q_fold=0.01 → clusters: [3585]
QF: 0.007
no shape_space
3585
59.94997914928745
2.7258689854369056
[c3c3] q_fold=0.01 → clusters: [3585]
QF: 0.008
no shape_space
3585
59.94997914928745
2.7258689854369056
[c3c3] q_fold=0.01 → clusters: [3585]
QF: 0.009
no shape_space
3585
59.94997914928745
2.7258689854369056
[c3c3] q_fold=0.01 → clusters: [3585]
QF: 0.01
no shape_space
3585
59.94997914928745
2.725868

In [19]:
configurations

{'c3c3': array([0.   , 0.001, 0.002, 0.003, 0.004, 0.005, 0.006, 0.007, 0.008,
        0.009, 0.01 ])}

In [11]:
result_dir = 'preclustering_results/minimal_q_fold_no_outlier'

mode_clusters_res = []

for filename in os.listdir(result_dir):
    if filename.endswith('_precluster.pkl'):
        # Load
        with open(os.path.join(result_dir, filename), 'rb') as f:
            result = pickle.load(f)
            print(len(result['clusters']))

5
6
8
6


In [ ]:
min_size = 3
scale = 12000

# Where you saved them
result_dir = 'preclustering_results'

mode_clusters_res = []

for filename in os.listdir(result_dir):
    if filename.endswith('_precluster.pkl'):
        # Load
        with open(os.path.join(result_dir, filename), 'rb') as f:
            result = pickle.load(f)

        name = result['name']
        clusters = result['clusters']
        outliers = result['outliers']
        scaled_coords_by_pucker = result['scaled_coords']

        print(name)

        # Map to sphere and angles for PNS input
        d2_s, d3_s, alpha_s, theta1, phi1, theta2, phi2 = scaled_coords_by_pucker.T

        # TODO run PN_G_S on (theta_i, phi_i), self.dists_ will return residuals, dists_[0] = theta, dists_[1] = phi since we're on S2
        S2_1 = spherical_to_vec(theta1, phi1)
        pns_S2_1 = PNS(mode='great', verbose=True).fit(S2_1)
        theta1, phi1 = pns_S2_1.dists_

        S2_2 = spherical_to_vec(theta2, phi2)
        pns_S2_2 = PNS(mode='great', verbose=True).fit(S2_2)
        theta2, phi2 = pns_S2_2.dists_

        # TODO substract the mean from d_i_s 
        V = np.column_stack([d2_s, d3_s])
        V -= np.mean(V, axis=0)

        # TODO run PN_G_S on S2_d (distances)
        # S2_pts = exponential_map(V, p=np.array([0,0,1]))
        S2_d = exponential_map(V, p=np.array([0,0,1])) # try this should be better
        pns_S2_d = PNS(mode='great', verbose=True).fit(S2_d)
        theta_d, phi_d = pns_S2_d.dists_

        # r = np.linalg.norm(S2_pts, axis=1)
        # theta_e_deg = np.degrees(np.arccos(np.clip(z/r, -1, 1)))
        # phi_e_deg = (np.degrees(np.arctan2(y, x)) + 360.0) % 360.0

        # TODO maybe add 180 for plots
        angle_matrix = np.column_stack([
            theta_d + 180,
            phi_d + 180,
            alpha_s,
            theta1 + 180,
            phi1 + 180,
            theta2 + 180,
            phi2 + 180
        ])
        # if filename == 'c2c2_precluster.pkl':
        #     break

        # Run PNS-based clustering
        mode_clusters, _ = refine_clusters_with_pns(
            scale=scale,
            data=angle_matrix,
            cluster_list=clusters,
            outlier_list=outliers,
            min_cluster_size=min_size
        )

        mode_clusters_res.append({
            'name': name,
            'mode_clusters': mode_clusters
        })

        print(f"[{name}] mode clusters done: {len(mode_clusters)} clusters")

# You can save final mode_clusters_res if needed
with open('mode_clusters_results.pkl', 'wb') as f:
    pickle.dump(mode_clusters_res, f)


In [10]:
angle_matrix.shape

(3585, 7)

'name': 'c3c2',
 'optimal_q_fold': 0.37,


 'name': 'c2c2',
 'optimal_q_fold': 0.31,

 'name': 'c3c2',
  'optimal_q_fold': 0.37,

q_fold=0.35 for c3c3, found 7 clusters

In [48]:
result_dir = 'postclustering_results'
filename = "pucker_indices.pkl"

with open(os.path.join(result_dir, filename), 'rb') as f:
    pucker_indices = pickle.load(f)

In [49]:
pucker_indices

{'c2c2': array([  16,   17,   52,   84,  174,  179,  202,  206,  308,  309,  341,
         500,  563,  574,  599,  642,  651,  652,  666,  800,  806,  807,
         808,  831,  841,  905, 1077, 1120, 1152, 1262, 1287, 1291, 1293,
        1294, 1312, 1313, 1352, 1394, 1395, 1396, 1417, 1458, 1476, 1477,
        1521, 1522, 1524, 1547, 1548, 1549, 1550, 1572, 1601, 1602, 1603,
        1610, 1694, 1764, 1765, 1772, 1789, 1842, 1846, 1847, 1852, 1928,
        1984, 1990, 2038, 2093, 2094, 2100, 2116, 2123, 2175, 2191, 2210,
        2238, 2257, 2258, 2277, 2278, 2279, 2285, 2307, 2316, 2317, 2330,
        2332, 2336, 2342, 2403, 2404, 2410, 2442, 2443, 2491, 2503, 2504,
        2535, 2545, 2548, 2549, 2578, 2676, 2758, 2926, 2932, 2938, 2939,
        2982, 3051, 3060, 3097, 3116, 3138, 3242, 3267, 3268, 3319, 3444,
        3445, 3446, 3539, 3592, 3645, 3646, 3682, 3683, 3684, 3874, 3875,
        3888, 3909, 3919, 3930, 3958, 4131]),
 'c2c3': array([  53,   64,   75,   85,   96,  172,  177, 

In [63]:
result_dir = 'postclustering_results'
filename = "minimal_q_fold_no_outlier_premerged_postcluster.pkl"
filename = "RNA_clusters.pickle"
filename = "no_cluster_sep.pkl"
filename = "fixed_cluster_sep_no_premerge_test.pkl"

with open(os.path.join(result_dir, filename), 'rb') as f:
    result_low_res = pickle.load(f)

In [64]:
result_low_res

[{'name': 'c2c2',
  'mode_clusters': [array([  84,  179,  341,  563,  599,  651,  807,  808, 1262, 1313, 1394,
          1396, 1458, 1477, 1602, 1603, 1764, 1842, 1847, 1928, 1984, 2093,
          2100, 2116, 2123, 2238, 2257, 2277, 2279, 2410, 2504, 2545, 2549,
          2578, 2676, 2926, 2932, 3051, 3060, 3116, 3138, 3242, 3267, 3444,
          3445, 3645, 3682, 3875, 3888, 3919, 3930]),
   array([  16,  308,  309,  642,  666,  806,  841, 1152, 1476, 1521, 1548,
          1549, 1550, 1601, 1772, 1846, 2038, 2307, 2330, 2403, 2548, 2758,
          2938, 3539, 3874, 3958]),
   array([ 202,  206,  500,  574,  800, 1120, 1294, 1395, 1522, 1524, 1610,
          1765, 2094, 2191, 2258, 2278, 2316, 2317, 2332, 2336, 2442, 3097,
          3268, 3446, 3683, 3909]),
   array([  52,  652,  831,  905, 1291, 1293, 1312, 1352, 1417, 1547, 1572,
          1694, 1852, 1990, 2342, 2443, 2491, 2503, 2982, 3319, 3592, 3646,
          4131]),
   array([  17,  174, 1077, 1287, 1789, 2175, 2210, 2285, 240

In [61]:
c = 0
for res in result_low_res:
    for arr in res['mode_clusters']:
        c += len(arr)

In [62]:
c

4213

In [3]:
result_dir = ''
filename = "/Users/kaisardauletbek/Downloads/mintage-code-dihedrals/out/saved_suite_lists/cluster_indices_c2c2_qfold_0.05.pickle"

with open(os.path.join(result_dir, filename), 'rb') as f:
    result_high_res = pickle.load(f)

In [14]:
result_low_res[3]

{'name': 'c2c3',
 'mode_clusters': [array([  0,   2,   4,   6,   9,  10,  12,  13,  15,  16,  19,  23,  24,
          25,  26,  33,  37,  40,  41,  42,  47,  51,  53,  55,  58,  61,
          62,  68,  74,  80,  82,  88,  89,  98,  99, 106, 109, 114, 121,
         134, 137, 144, 145, 146, 147, 149, 154, 157, 162, 166, 168, 169,
         171, 172, 174, 177, 180, 184, 186, 190, 191, 195, 196, 209, 219,
         220]),
  array([  1,   8,  17,  21,  29,  34,  36,  38,  39,  43,  48,  49,  52,
          56,  57,  59,  63,  64,  69,  70,  75,  78,  84,  92,  93,  94,
          96, 102, 104, 110, 111, 112, 115, 122, 128, 143, 148, 158, 163,
         165, 170, 179, 182, 183, 187, 194, 198, 203, 204, 205, 206, 207,
         208, 211, 213, 214]),
  array([  7,  20,  30,  31,  35,  45,  50,  60,  65,  71,  72,  81,  83,
          87,  91,  95,  97, 108, 116, 123, 125, 127, 130, 133, 139, 140,
         142, 150, 160, 167, 175, 189, 192, 199, 200, 212, 216]),
  array([  3,  11,  27,  28,  73,  79, 

In [5]:
result_high_res

[[1,
  2,
  4,
  11,
  13,
  16,
  17,
  19,
  20,
  23,
  25,
  26,
  27,
  31,
  32,
  34,
  36,
  38,
  40,
  47,
  51,
  55,
  56,
  58,
  60,
  64,
  67,
  68,
  74,
  75,
  76,
  79,
  81,
  83,
  85,
  86,
  88,
  89,
  90,
  92,
  94,
  95,
  97,
  99,
  104,
  109,
  110,
  113,
  118,
  119,
  125,
  126,
  128,
  133,
  137],
 [3,
  29,
  30,
  37,
  41,
  43,
  53,
  54,
  57,
  63,
  66,
  71,
  72,
  77,
  78,
  93,
  98,
  100,
  102,
  103,
  106,
  107,
  112,
  115,
  116,
  117,
  120,
  121,
  127,
  131,
  132,
  134,
  135],
 [5, 10, 12, 14, 21, 22, 35, 39, 61, 65, 69, 73, 80, 82, 111, 114, 129],
 [9, 15, 24, 28, 42, 44, 49, 50, 52, 62, 84, 91, 96, 123, 124],
 [0, 7, 8, 18, 33, 45, 46, 48, 59, 70, 87, 101, 105, 108, 122, 130, 136]]

In [6]:
# Define the two clusterings
experiment1 = result_low_res[0]

experiment2 = result_high_res

# Convert experiment2 to numpy arrays for consistency
experiment2_arrays = [np.array(cluster) for cluster in experiment2]

# Create confusion matrix
def create_confusion_matrix(clustering1, clustering2):
    """
    Create a confusion matrix between two clusterings.
    
    Parameters:
    -----------
    clustering1 : list of arrays
        First clustering (rows of confusion matrix)
    clustering2 : list of arrays
        Second clustering (columns of confusion matrix)
    
    Returns:
    --------
    confusion_matrix : np.ndarray
        Matrix where entry (i, j) is the number of items in cluster i of 
        clustering1 that are also in cluster j of clustering2
    """
    n_clusters1 = len(clustering1)
    n_clusters2 = len(clustering2)
    confusion_matrix = np.zeros((n_clusters1, n_clusters2), dtype=int)
    
    for i, cluster1 in enumerate(clustering1):
        for j, cluster2 in enumerate(clustering2):
            # Count intersection
            intersection = np.intersect1d(cluster1, cluster2)
            confusion_matrix[i, j] = len(intersection)
    
    return confusion_matrix

# Create the confusion matrix
conf_matrix = create_confusion_matrix(experiment1['mode_clusters'], experiment2_arrays)

print("Confusion Matrix:")
print("Rows: Experiment 1 clusters (mode_clusters)")
print("Columns: Experiment 2 clusters")
print("\n", conf_matrix)

# Calculate clustering comparison metrics
from sklearn.metrics import adjusted_rand_score, normalized_mutual_info_score

def create_label_vectors(clustering, n_items):
    """
    Convert clustering to label vector format for sklearn metrics.
    """
    labels = np.full(n_items, -1, dtype=int)
    for cluster_idx, cluster in enumerate(clustering):
        labels[cluster] = cluster_idx
    return labels

# Get all unique items to determine total number
all_items_exp1 = np.concatenate(experiment1['mode_clusters'])
all_items_exp2 = np.concatenate(experiment2_arrays)
all_items = np.unique(np.concatenate([all_items_exp1, all_items_exp2]))
n_items = len(all_items)

# Create label vectors
labels1 = create_label_vectors(experiment1['mode_clusters'], n_items=max(all_items) + 1)
labels2 = create_label_vectors(experiment2_arrays, n_items=max(all_items) + 1)

# Filter to only items present in both clusterings
common_items = np.intersect1d(all_items_exp1, all_items_exp2)
if len(common_items) > 0:
    labels1_filtered = labels1[common_items]
    labels2_filtered = labels2[common_items]
    
    # Calculate metrics
    ari = adjusted_rand_score(labels1_filtered, labels2_filtered)
    nmi = normalized_mutual_info_score(labels1_filtered, labels2_filtered)
    
    print(f"\nClustering Comparison Metrics (on {len(common_items)} common items):")
    print(f"  Adjusted Rand Index (ARI): {ari:.4f}")
    print(f"  Normalized Mutual Information (NMI): {nmi:.4f}")
    print(f"  (ARI ranges from -1 to 1, higher is better; NMI ranges from 0 to 1, higher is better)")

# Visualize the confusion matrix
fig, ax = plt.subplots(figsize=(12, 9))
im = ax.imshow(conf_matrix, cmap='Blues', aspect='auto', vmin=0, vmax=conf_matrix.max())

# Add text annotations with percentages
for i in range(len(experiment1['mode_clusters'])):
    for j in range(len(experiment2_arrays)):
        count = conf_matrix[i, j]
        if count > 0:
            # Calculate percentage of row cluster
            pct_row = (count / len(experiment1['mode_clusters'][i])) * 100
            # Calculate percentage of column cluster
            pct_col = (count / len(experiment2_arrays[j])) * 100
            text_str = f"{count}\n({pct_row:.0f}%/{pct_col:.0f}%)"
        else:
            text_str = "0"
        text = ax.text(j, i, text_str,
                      ha="center", va="center", 
                      color="white" if conf_matrix[i, j] > conf_matrix.max()/3 else "black",
                      fontsize=9, fontweight='bold')

# Set labels
ax.set_xlabel('Experiment 2 Clusters', fontsize=12, fontweight='bold')
ax.set_ylabel('Experiment 1 Clusters (mode_clusters)', fontsize=12, fontweight='bold')
ax.set_title('Confusion Matrix: Experiment 1 vs Experiment 2\n(Format: count (row% / col%))', 
             fontsize=14, fontweight='bold')

# Set tick labels
ax.set_xticks(np.arange(len(experiment2_arrays)))
ax.set_yticks(np.arange(len(experiment1['mode_clusters'])))
ax.set_xticklabels([f'Cluster {i+1}\n(n={len(c)})' for i, c in enumerate(experiment2_arrays)])
ax.set_yticklabels([f'Cluster {i+1}\n(n={len(c)})' for i, c in enumerate(experiment1['mode_clusters'])])

# Add colorbar
cbar = plt.colorbar(im, ax=ax)
cbar.set_label('Number of Overlapping Items', rotation=270, labelpad=20)

plt.tight_layout()
# Use display instead of show() for better Jupyter compatibility
from IPython.display import display
display(fig)
plt.close(fig)

# Print cluster sizes for reference
print("\nExperiment 1 cluster sizes:", [len(c) for c in experiment1['mode_clusters']])
print("Experiment 2 cluster sizes:", [len(c) for c in experiment2_arrays])
print(f"\nTotal items in Experiment 1: {sum(len(c) for c in experiment1['mode_clusters'])}")
print(f"Total items in Experiment 2: {sum(len(c) for c in experiment2_arrays)}")


Confusion Matrix:
Rows: Experiment 1 clusters (mode_clusters)
Columns: Experiment 2 clusters

 [[ 2  0  0 13 11]
 [21  0  0  2  0]
 [10  1  1  0  0]
 [ 3 32 16  0  0]
 [19  0  0  0  6]]

Clustering Comparison Metrics (on 137 common items):
  Adjusted Rand Index (ARI): 0.3606
  Normalized Mutual Information (NMI): 0.5316
  (ARI ranges from -1 to 1, higher is better; NMI ranges from 0 to 1, higher is better)


<Figure size 1200x900 with 2 Axes>


Experiment 1 cluster sizes: [26, 23, 12, 52, 25]
Experiment 2 cluster sizes: [55, 33, 17, 15, 17]

Total items in Experiment 1: 138
Total items in Experiment 2: 137


In [13]:
from utils import Suite_class as Suite_class
with open('/Users/kaisardauletbek/Documents/GitHub/RNA-Classification/data/RNA_suites_with_classes.pickle', 'rb') as f:
    new_data = pickle.load(f)

ModuleNotFoundError: No module named 'Suite_class'